
import "../../globals.css";

export const metadata = {
	title: "URLShortener - User URL",
	description: "Generated by create next app",
};

export default function UrlRootLayout({ children }) {
	return (
		<>
			{children}
		</>
	);
}
