import Toast from "@/components/toast";
import ".././globals.css";

export const metadata = {
	title: "URLShortener - Admin Dashboard",
	description: "Generated by create next app",
};

export default function EditParametersRootLayout({ children }) {
	return (
		<>
			<Toast />
			{children}
		</>
	);
}
